# PyTorch Examples

## imports

In [6]:
import torch
import torch.nn as nn

from torch.utils.data import Dataset

### torch.sign

In [9]:
a = torch.tensor([[0.7, -1.2, 0., 2.3], 
                  [1.2, 0.7, 0., 1.3]])
a

tensor([[ 0.7000, -1.2000,  0.0000,  2.3000],
        [ 1.2000,  0.7000,  0.0000,  1.3000]])

In [10]:
torch.sign(a)

tensor([[ 1., -1.,  0.,  1.],
        [ 1.,  1.,  0.,  1.]])

In [12]:
torch.sum(torch.sign(a), dim=1).data

tensor([1., 3.])

### nn.GRU

In [13]:
gru = nn.GRU(input_size=10, 
             hidden_size=20, 
             batch_first=True, 
             bidirectional=True)

In [43]:
input_ = torch.randn(5, 3, 10)

# (num_layers*num_directions, batch, num_directions*hidden_size)
h0 = torch.randn(2, 5, 20)  

In [39]:
input_.size()

torch.Size([5, 3, 10])

In [40]:
output, hn = gru(input_, h0)

In [45]:
output.size()  # backward, forward 

torch.Size([5, 3, 40])

In [42]:
hn.shape

torch.Size([2, 5, 20])

### torch.squeeze

- Returns a tensor with all the dimensions of `input` of size 1 removed.

- For example, if input is of shape: $(A \times 1 \times B \times C \times 1 \times D)$ then the out tensor will be of shape: $(A \times B \times C \times D)$.

In [55]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [57]:
y = x.squeeze()

In [58]:
y.size()

torch.Size([2, 2, 2])

In [61]:
y = x.squeeze(dim=1)
y.size()

torch.Size([2, 2, 1, 2])

### torch.unsqueeze

- Returns a new tensor with a dimension of size one inserted at the specified position.

- The returned tensor shares the same underlying data with this tensor.

In [62]:
x = torch.tensor([1, 2, 3, 4])

In [64]:
x

tensor([1, 2, 3, 4])

In [65]:
x.unsqueeze(0)

tensor([[1, 2, 3, 4]])

In [66]:
x.unsqueeze(1)

tensor([[1],
        [2],
        [3],
        [4]])

### Dataset

In [5]:
Dataset.__dict__

mappingproxy({'__module__': 'torch.utils.data.dataset',
              '__doc__': 'An abstract class representing a :class:`Dataset`.\n\n    All datasets that represent a map from keys to data samples should subclass\n    it. All subclasses should overwrite :meth:`__getitem__`, supporting fetching a\n    data sample for a given key. Subclasses could also optionally overwrite\n    :meth:`__len__`, which is expected to return the size of the dataset by many\n    :class:`~torch.utils.data.Sampler` implementations and the default options\n    of :class:`~torch.utils.data.DataLoader`.\n\n    .. note::\n      :class:`~torch.utils.data.DataLoader` by default constructs a index\n      sampler that yields integral indices.  To make it work with a map-style\n      dataset with non-integral indices/keys, a custom sampler must be provided.\n    ',
              '__getitem__': <function torch.utils.data.dataset.Dataset.__getitem__(self, index)>,
              '__add__': <function torch.utils.data.da

### torch.cuda

In [8]:
torch.cuda.is_available()

True

In [12]:
torch.cuda.current_device()

0

In [13]:
torch.cuda.device_count()

2

### torch.tensor

In [39]:
from torch.autograd import Variable

In [37]:
x = torch.LongTensor([1, 2, 3])

In [38]:
x.requires_grad

False

In [45]:
x = Variable(x.float())

In [46]:
x.requires_grad

False

In [43]:
x

tensor([1, 2, 3])

In [51]:
print(f'{1:02d}')

01
